# Generated by Django 6.0.3 on 2026-04-23 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_userconsent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="fundraise_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_donation",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидает"),
                    ("completed", "Завершена"),
                    ("failed", "Ошибка"),
                ],
                default="completed",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Fundraise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название сбора"),
                ),
                ("description", models.TextField(verbose_name="Описание цели")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medical", "Медицина и здоровье"),
                            ("education", "Образование"),
                            ("animal", "Помощь животным"),
                            ("ecology", "Экология"),
                            ("sport", "Спорт"),
                            ("art", "Искусство и культура"),
                            ("business", "Бизнес и стартапы"),
                            ("other", "Другое"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Категория",
                    ),
                ),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Целевая сумма"
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Собрано",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активный"),
                            ("completed", "Завершен"),
                            ("cancelled", "Отменен"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на изображение"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="Рекомендуемый"),
                ),
                (
                    "donors_count",
                    models.IntegerField(default=0, verbose_name="Количество донатеров"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundraises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сбор средств",
                "verbose_name_plural": "Сборы средств",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сообщение поддержки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Анонимно"),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Донатер",
                    ),
                ),
                (
                    "fundraise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="main.fundraise",
                        verbose_name="Сбор",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="UserConsent",
        ),
    ]
