# Generated by Django 6.0.3 on 2026-04-23 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_transaction_fundraise_id_transaction_is_donation_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("accept", "Принятие"), ("revoke", "Отзыв")],
                        max_length=20,
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("privacy", "Политика конфиденциальности"),
                            ("terms", "Пользовательское соглашение"),
                            ("cookies", "Политика cookies"),
                            ("marketing", "Маркетинговые уведомления"),
                            ("data_processing", "Обработка персональных данных"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=10)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог согласий",
                "verbose_name_plural": "Логи согласий",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consent_type",
                    models.CharField(
                        choices=[
                            ("privacy", "Политика конфиденциальности"),
                            ("terms", "Пользовательское соглашение"),
                            ("cookies", "Политика cookies"),
                            ("marketing", "Маркетинговые уведомления"),
                            ("data_processing", "Обработка персональных данных"),
                        ],
                        max_length=20,
                        verbose_name="Тип согласия",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        choices=[
                            ("1.0", "Версия 1.0"),
                            ("1.1", "Версия 1.1"),
                            ("2.0", "Версия 2.0"),
                        ],
                        default="1.0",
                        max_length=10,
                        verbose_name="Версия",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Согласие принято"),
                ),
                (
                    "agreed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата согласия"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User-Agent"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата отзыва"
                    ),
                ),
                (
                    "revocation_reason",
                    models.TextField(
                        blank=True, null=True, verbose_name="Причина отзыва"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Согласие пользователя",
                "verbose_name_plural": "Согласия пользователей",
                "ordering": ["-agreed_at"],
                "unique_together": {("user", "consent_type", "version")},
            },
        ),
    ]
