# Generated by Django 6.0.3 on 2026-04-24 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_fundraise_total_commission_commissiontransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Сумма вывода"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("card", "Банковская карта"),
                            ("sbp", "СБП"),
                            ("yoomoney", "ЮMoney"),
                            ("crypto", "Криптовалюта"),
                        ],
                        max_length=20,
                        verbose_name="Способ вывода",
                    ),
                ),
                (
                    "payment_details",
                    models.JSONField(
                        help_text="Данные для перевода (карта, номер телефона, кошелек и т.д.)",
                        verbose_name="Реквизиты для вывода",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("processing", "В обработке"),
                            ("completed", "Выполнен"),
                            ("rejected", "Отклонен"),
                            ("cancelled", "Отменен пользователем"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий администратора"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="ID транзакции в платежной системе",
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="processed_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Обработал",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на вывод",
                "verbose_name_plural": "Заявки на вывод",
                "ordering": ["-created_at"],
            },
        ),
    ]
