# Generated by Django 6.0.3 on 2026-04-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_kycdocument_paymenttransaction_securitylog_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundraise",
            name="total_commission",
        ),
    ]
