# Generated by Django 6.0.3 on 2026-04-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_remove_fundraise_total_commission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "USDT (TRC20)"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("TON", "Toncoin"),
                        ],
                        default="USDT",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=8, default=0.0, max_digits=20),
                ),
                (
                    "wallet_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_balance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CryptoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("deposit", "Пополнение"),
                            ("withdrawal", "Вывод"),
                            ("transfer", "Перевод"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("USDT", "USDT (TRC20)"),
                            ("BTC", "Bitcoin"),
                            ("ETH", "Ethereum"),
                            ("TON", "Toncoin"),
                        ],
                        default="USDT",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "amount_rub",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает"),
                            ("processing", "В обработке"),
                            ("completed", "Завершена"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменена"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("tx_hash", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "from_address",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("to_address", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crypto_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
