# Generated by Django 5.2.17 on 2026-09-12 14:58

import django.core.validators
import main.storage
import main.utils.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_cryptobalance_cryptotransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cryptobalance",
            name="user",
        ),
        migrations.RemoveField(
            model_name="cryptotransaction",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="commissiontransaction",
            options={
                "verbose_name": "Комиссия сервиса",
                "verbose_name_plural": "Комиссии сервиса",
            },
        ),
        migrations.AddField(
            model_name="donation",
            name="refunded_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Возвращено",
            ),
        ),
        migrations.AddField(
            model_name="donation",
            name="refunded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата возврата"
            ),
        ),
        migrations.AddField(
            model_name="securitylog",
            name="username_attempted",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="transaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("transfer", "Перевод пользователю"),
                    ("donation", "Пожертвование в сбор"),
                    ("topup", "Пополнение баланса"),
                    ("refund", "Возврат"),
                    ("withdrawal", "Вывод средств"),
                ],
                db_index=True,
                default="transfer",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userverification",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Данные поданы"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrequest",
            name="payment_details_masked",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Реквизиты (маскированные)",
            ),
        ),
        migrations.AlterField(
            model_name="balance",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="commissiontransaction",
            name="percent",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Сумма"
            ),
        ),
        migrations.AlterField(
            model_name="kycdocument",
            name="document_image",
            field=models.FileField(
                storage=main.storage.PrivateMediaStorage(), upload_to="kyc/%Y/%m/%d/"
            ),
        ),
        migrations.AlterField(
            model_name="kycdocument",
            name="document_number",
            field=main.utils.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="paymenttransaction",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Банковская карта"),
                    ("sbp", "СБП"),
                    ("yoomoney", "ЮMoney"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="securitylog",
            name="user_agent",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="address",
            field=main.utils.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="passport_number",
            field=main.utils.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="userverification",
            name="passport_series",
            field=main.utils.fields.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Сумма вывода",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="payment_details",
            field=main.utils.fields.EncryptedJSONField(
                blank=True,
                default=dict,
                help_text="Данные для перевода (хранятся в зашифрованном виде)",
                verbose_name="Реквизиты для вывода",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card", "Банковская карта"),
                    ("sbp", "СБП"),
                    ("yoomoney", "ЮMoney"),
                ],
                max_length=20,
                verbose_name="Способ вывода",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "На рассмотрении"),
                    ("processing", "В обработке"),
                    ("completed", "Выполнен"),
                    ("rejected", "Отклонен"),
                    ("cancelled", "Отменен пользователем"),
                    ("failed", "Ошибка выплаты"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["fundraise", "-created_at"],
                name="main_donati_fundrai_dcbfe8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["action", "-created_at"], name="main_securi_action_b94b86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="securitylog",
            index=models.Index(
                fields=["ip_address", "-created_at"],
                name="main_securi_ip_addr_ca352c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["sender", "-created_at"], name="main_transa_sender__ed9f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["receiver", "-created_at"],
                name="main_transa_receive_57579a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="withdrawalrequest",
            index=models.Index(
                fields=["user", "-created_at"], name="main_withdr_user_id_64e807_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="balance",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)),
                name="balance_amount_non_negative",
            ),
        ),
        migrations.DeleteModel(
            name="CryptoBalance",
        ),
        migrations.DeleteModel(
            name="CryptoTransaction",
        ),
    ]
