# Generated by Django 5.2.17 on 2026-09-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_encrypt_sensitive_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentlog",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("terms", "Пользовательское соглашение (акцепт оферты)"),
                    ("data_processing", "Обработка персональных данных (ст. 9 152-ФЗ)"),
                    (
                        "distribution",
                        "Распространение персональных данных (ст. 10.1 152-ФЗ)",
                    ),
                    ("cookies", "Политика cookies"),
                    ("marketing", "Маркетинговые уведомления"),
                    ("privacy", "Политика конфиденциальности (устаревший тип)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userconsent",
            name="consent_type",
            field=models.CharField(
                choices=[
                    ("terms", "Пользовательское соглашение (акцепт оферты)"),
                    ("data_processing", "Обработка персональных данных (ст. 9 152-ФЗ)"),
                    (
                        "distribution",
                        "Распространение персональных данных (ст. 10.1 152-ФЗ)",
                    ),
                    ("cookies", "Политика cookies"),
                    ("marketing", "Маркетинговые уведомления"),
                    ("privacy", "Политика конфиденциальности (устаревший тип)"),
                ],
                max_length=20,
                verbose_name="Тип согласия",
            ),
        ),
    ]
