# Generated by Django 5.2.17 on 2026-09-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_consentlog_consent_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userconsent",
            name="version",
            field=models.CharField(default="1.0", max_length=10, verbose_name="Версия"),
        ),
    ]
