# Generated by Django 5.2.17 on 2026-09-12 17:09

import django.db.models.deletion
import main.storage
from django.conf import settings
from django.db import migrations, models


def grandfather_existing(apps, schema_editor):
    """
    Разметка сборов, существовавших до появления модерации.

    Новое поле по умолчанию 'draft', и без этого шага все прежние сборы
    разом исчезли бы с витрины. Но и объявить их одобренными нельзя:
    их никто не проверял, а именно непроверенный сбор — тот самый риск,
    ради которого модерация вводится.

    Поэтому действующие сборы отправляются на проверку: они перестают
    принимать пожертвования до решения модератора. Завершённые и отменённые
    помечаются одобренными — денег они не принимают (accepts_donations
    требует status='active'), а скрывать историю расчётов с донорами нельзя.
    """
    Fundraise = apps.get_model('main', 'Fundraise')

    Fundraise.objects.filter(status='active').update(moderation_status='pending')
    Fundraise.objects.filter(status__in=['completed', 'cancelled']).update(
        moderation_status='approved',
    )


def noop(apps, schema_editor):
    """Откат: поля удаляются следующей операцией, восстанавливать нечего."""


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_userconsent_version"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FundraiseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "medical",
                                "Медицинский документ (выписка, направление, счёт)",
                            ),
                            ("invoice", "Счёт или смета"),
                            ("official", "Официальный документ (справка, решение)"),
                            ("other", "Иное подтверждение"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        storage=main.storage.PrivateMediaStorage(),
                        upload_to="fundraise-docs/%Y/%m/",
                        verbose_name="Файл",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Пояснение автора"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Загружен"),
                ),
            ],
            options={
                "verbose_name": "Документ к сбору",
                "verbose_name_plural": "Документы к сборам",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="fundraise",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата проверки"
            ),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_fundraises",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Проверил",
            ),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="moderation_comment",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Показывается автору сбора",
                verbose_name="Комментарий модератора",
            ),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="moderation_status",
            field=models.CharField(
                choices=[
                    ("draft", "Не отправлен на проверку"),
                    ("pending", "На проверке"),
                    ("approved", "Одобрен"),
                    ("changes_requested", "Требуются уточнения"),
                    ("rejected", "Отклонён"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
                verbose_name="Статус проверки",
            ),
        ),
        migrations.AddField(
            model_name="fundraise",
            name="submitted_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Отправлен на проверку"
            ),
        ),
        migrations.AlterField(
            model_name="fundraise",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("active", "Активный"),
                    ("completed", "Завершен"),
                    ("cancelled", "Отменен"),
                ],
                default="draft",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AddIndex(
            model_name="fundraise",
            index=models.Index(
                fields=["moderation_status", "status"],
                name="main_fundra_moderat_3fab33_idx",
            ),
        ),
        migrations.AddField(
            model_name="fundraisedocument",
            name="fundraise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="main.fundraise",
                verbose_name="Сбор",
            ),
        ),
        migrations.RunPython(grandfather_existing, noop),
    ]
