# Generated by Django 5.2.17 on 2026-09-12 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_fundraise_moderation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDataAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("passport", "Паспортные данные"),
                            (
                                "kyc_document",
                                "Скан документа, удостоверяющего личность",
                            ),
                            (
                                "fundraise_document",
                                "Документ к сбору (в т. ч. сведения о здоровье)",
                            ),
                            ("payment_details", "Платёжные реквизиты"),
                            ("contact", "Контактные данные"),
                            ("export", "Полная выгрузка данных пользователя"),
                            ("other", "Иное"),
                        ],
                        max_length=32,
                        verbose_name="Категория данных",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Основание"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Объект"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, default="", verbose_name="User-Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда"
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pd_accesses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто обратился",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pd_accessed",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Чьи данные",
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение к персональным данным",
                "verbose_name_plural": "Журнал доступа к персональным данным",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["subject", "-created_at"],
                        name="main_person_subject_3eafb8_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="main_person_actor_i_fc1f80_idx",
                    ),
                ],
            },
        ),
    ]
