# Generated by Django 5.2.17 on 2026-09-12 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_pd_access_log"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountRestriction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("suspended", "Операции приостановлены"),
                            ("blocked", "Учётная запись заблокирована"),
                        ],
                        max_length=20,
                        verbose_name="Вид ограничения",
                    ),
                ),
                (
                    "ground",
                    models.CharField(
                        choices=[
                            ("terms_violation", "Нарушение раздела 8 оферты"),
                            ("fraud_suspicion", "Признаки мошенничества"),
                            ("authority_request", "Требование уполномоченного органа"),
                            (
                                "verification_failed",
                                "Недостоверные сведения при верификации",
                            ),
                            ("age_restriction", "Пользователь младше 18 лет"),
                        ],
                        max_length=30,
                        verbose_name="Основание",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="Показывается пользователю и отправляется ему письмом",
                        verbose_name="Причина для пользователя",
                    ),
                ),
                (
                    "internal_note",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Пользователю не показывается",
                        verbose_name="Служебная заметка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Когда применено"
                    ),
                ),
                (
                    "notify_deadline",
                    models.DateTimeField(verbose_name="Срок уведомления"),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Уведомление отправлено"
                    ),
                ),
                (
                    "appeal_deadline",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Срок рассмотрения возражений",
                    ),
                ),
                (
                    "appeal_text",
                    models.TextField(
                        blank=True, default="", verbose_name="Объяснения пользователя"
                    ),
                ),
                (
                    "appeal_submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Возражение подано"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("upheld", "Ограничение оставлено в силе"),
                            ("lifted", "Ограничение снято"),
                        ],
                        default="",
                        max_length=20,
                        verbose_name="Решение по возражению",
                    ),
                ),
                (
                    "decision_comment",
                    models.TextField(
                        blank=True, default="", verbose_name="Мотивировка решения"
                    ),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата решения"
                    ),
                ),
                (
                    "lifted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Снято"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restrictions_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто применил",
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restrictions_decided",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто рассмотрел",
                    ),
                ),
                (
                    "lifted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="restrictions_lifted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто снял",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restrictions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ограничение по учётной записи",
                "verbose_name_plural": "Ограничения по учётным записям",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "lifted_at"],
                        name="main_accoun_user_id_e77ffc_idx",
                    )
                ],
            },
        ),
    ]
