# Generated by Django 5.2.17 on 2026-09-12 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_account_restriction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DataBreachIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detected_at",
                    models.DateTimeField(
                        help_text="Момент, с которого считаются 24 и 72 часа",
                        verbose_name="Когда стало известно",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("suspected", "Подозрение на инцидент"),
                            ("confirmed", "Подтверждённый инцидент"),
                            ("false_alarm", "Не подтвердился"),
                        ],
                        default="suspected",
                        max_length=20,
                        verbose_name="Квалификация",
                    ),
                ),
                ("summary", models.CharField(max_length=255, verbose_name="Кратко")),
                (
                    "description",
                    models.TextField(verbose_name="Обстоятельства инцидента"),
                ),
                (
                    "data_categories",
                    models.TextField(
                        help_text="Какие именно данные затронуты: паспорт, реквизиты, контакты…",
                        verbose_name="Категории данных",
                    ),
                ),
                (
                    "affected_count",
                    models.IntegerField(
                        default=0, verbose_name="Число затронутых субъектов"
                    ),
                ),
                (
                    "suspected_cause",
                    models.TextField(
                        blank=True, default="", verbose_name="Предполагаемая причина"
                    ),
                ),
                (
                    "initial_notice_deadline",
                    models.DateTimeField(
                        verbose_name="Срок первичного уведомления (24 ч)"
                    ),
                ),
                (
                    "initial_notice_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Первичное уведомление отправлено",
                    ),
                ),
                (
                    "initial_notice_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Входящий номер РКН (первичное)",
                    ),
                ),
                (
                    "final_notice_deadline",
                    models.DateTimeField(
                        verbose_name="Срок уведомления о расследовании (72 ч)"
                    ),
                ),
                (
                    "final_notice_sent_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Уведомление о расследовании отправлено",
                    ),
                ),
                (
                    "final_notice_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Входящий номер РКН (по расследованию)",
                    ),
                ),
                (
                    "investigation_result",
                    models.TextField(
                        blank=True, default="", verbose_name="Результаты расследования"
                    ),
                ),
                (
                    "measures_taken",
                    models.TextField(
                        blank=True, default="", verbose_name="Принятые меры"
                    ),
                ),
                (
                    "subjects_notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Субъекты уведомлены"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Запись создана"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="breach_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто зарегистрировал",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инцидент с персональными данными",
                "verbose_name_plural": "Инциденты с персональными данными",
                "ordering": ["-detected_at"],
            },
        ),
    ]
