# Generated by Django 5.2.17 on 2026-09-12 18:22

from django.db import migrations, models


def backfill_closed_at(apps, schema_editor):
    """
    Отметка о закрытии для сборов, закрытых до появления поля.

    Точного момента закрытия у них нет — берётся дата создания. Это
    заведомо раньше настоящего закрытия, то есть срок хранения документов
    к ним наступит раньше обещанного, а не позже: в сторону уничтожения
    данных, а не их хранения сверх срока.
    """
    Fundraise = apps.get_model('main', 'Fundraise')
    for fundraise in Fundraise.objects.filter(
        status__in=['completed', 'cancelled'], closed_at__isnull=True,
    ):
        fundraise.closed_at = fundraise.created_at
        fundraise.save(update_fields=['closed_at'])


def noop(apps, schema_editor):
    """Откат: поле удаляется следующей операцией."""


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_breach_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="fundraise",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Закрыт"),
        ),
        migrations.RunPython(backfill_closed_at, noop),
    ]
