# Generated by Django 5.2.17 on 2026-09-13 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    """
    Учётные записи, существовавшие до введения проверки адреса.

    Объявить их подтверждёнными было бы неправдой: адреса никто не проверял.
    Но и отнять у людей вывод средств задним числом нельзя — они не давали
    повода и даже не узнают, почему перестало работать.

    Поэтому им ставится отдельная отметка is_legacy: ограничения на них не
    действуют, но в админке видно, что подтверждения не было. Чтобы
    потребовать подтверждение и от них, достаточно снять этот флаг —
    и людям стоит сказать об этом заранее.
    """
    User = apps.get_model('auth', 'User')
    EmailConfirmation = apps.get_model('main', 'EmailConfirmation')

    EmailConfirmation.objects.bulk_create(
        [
            EmailConfirmation(user_id=user_id, is_legacy=True)
            for user_id in User.objects.values_list('id', flat=True)
        ],
        ignore_conflicts=True,
    )


def noop(apps, schema_editor):
    """Откат: таблица удаляется следующей операцией."""


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_fundraise_closed_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Подтверждён"
                    ),
                ),
                (
                    "confirmed_email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Фиксируется отдельно: при смене адреса подтверждение перестаёт действовать",
                        max_length=254,
                        verbose_name="Подтверждённый адрес",
                    ),
                ),
                (
                    "last_sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Письмо отправлено"
                    ),
                ),
                (
                    "is_legacy",
                    models.BooleanField(
                        default=False,
                        verbose_name="Зарегистрирован до введения проверки",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_confirmation",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подтверждение email",
                "verbose_name_plural": "Подтверждения email",
            },
        ),
            migrations.RunPython(grandfather_existing_users, noop),
    ]
