"""
Django settings for angelsheart project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
import warnings
from decimal import Decimal

# Базовая директория проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Создаем папку для логов, если её нет
LOG_DIR = BASE_DIR / 'logs'
if not os.path.exists(LOG_DIR):
    os.makedirs(LOG_DIR)

# Игнорируем предупреждение DRF
warnings.filterwarnings(
    'ignore',
    message='min_value should be an integer or Decimal instance'
)

# ==================== БЕЗОПАСНОСТЬ ====================

from django.core.exceptions import ImproperlyConfigured

# SECURITY WARNING: don't run with debug turned on in production!
# По умолчанию False: забытая переменная окружения не должна поднимать прод в debug-режиме.
DEBUG = os.environ.get('DEBUG', 'False') == 'True'


def _required_secret(name, dev_default):
    """Секрет обязателен в проде и допускает заглушку только в DEBUG."""
    value = os.environ.get(name)
    if value:
        return value
    if DEBUG:
        return dev_default
    raise ImproperlyConfigured(
        f'Переменная окружения {name} не задана. '
        f'Запуск с DEBUG=False без неё небезопасен.'
    )


SECRET_KEY = _required_secret(
    'DJANGO_SECRET_KEY',
    'django-insecure-dev-only-6f(=+sxd@6&furo8281_sq@_e3*@5$=o77a#v2%49emje)%b12',
)

# Разрешенные хосты
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]', 'testserver']
else:
    ALLOWED_HOSTS = [
        host.strip()
        for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
        if host.strip()
    ]
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured('ALLOWED_HOSTS не задан при DEBUG=False.')

# Формы и вебхуки приходят по HTTPS с боевого домена
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# За обратным прокси (nginx) определяем HTTPS по заголовку
if os.environ.get('BEHIND_PROXY', 'False') == 'True':
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Сколько прокси перед приложением: столько последних адресов
    # в X-Forwarded-For можно считать доверенными (см. main/utils/request_meta.py)
    TRUSTED_PROXY_COUNT = int(os.environ.get('TRUSTED_PROXY_COUNT', '1'))
else:
    TRUSTED_PROXY_COUNT = 0

# Безопасность
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# CSRF
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'

# Безопасность (зависит от режима)
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ==================== ЛИМИТЫ ====================

MIN_WITHDRAWAL_AMOUNT = Decimal('500')
MAX_WITHDRAWAL_AMOUNT = Decimal('100000')

MIN_TOPUP_AMOUNT = Decimal('1')
MAX_TOPUP_AMOUNT = Decimal('100000')

MIN_DONATION_AMOUNT = Decimal('1')
MAX_DONATION_AMOUNT = Decimal('1000000')

# Единственный источник правды о комиссии: раньше значение было продублировано
# в settings, в шаблоне вью и в API, и все три расходились с офертой.
# Изменение этого числа обязано сопровождаться правкой пользовательского соглашения.
DONATION_COMMISSION_PERCENT = Decimal(os.environ.get('DONATION_COMMISSION_PERCENT', '0'))

# Банки для выплат через СБП: идентификаторы берутся из личного кабинета
# ЮKassa (продукт «Выплаты»). Формат: SBP_BANKS="100000000111:Сбербанк,...".
#
# Пока список пуст, способ «СБП» не предлагается пользователю вовсе. Раньше
# он предлагался всегда, а выплата по нему уходила в ЮKassa без обязательного
# идентификатора банка и неизбежно заканчивалась отказом — человек получал
# «выплата не выполнена» без объяснения причины.
SBP_BANKS = {
    part.split(':', 1)[0].strip(): part.split(':', 1)[1].strip()
    for part in os.environ.get('SBP_BANKS', '').split(',')
    if ':' in part
}

# Аккаунт, на который зачисляется комиссия. Без него удержанные деньги
# исчезали бы из системы. Создаётся: manage.py create_service_account
SERVICE_ACCOUNT_USERNAME = os.environ.get('SERVICE_ACCOUNT_USERNAME', 'service-account')

# ==================== МОДЕРАЦИЯ СБОРОВ ====================
# Раньше модерации не было: сбор на 10 млн «на лечение» публиковался
# мгновенно и без документов. Пороги ниже определяют, какая проверка
# личности нужна автору под заявленную сумму.

# До этой суммы достаточно подтверждённых паспортных данных
FUNDRAISE_BASIC_VERIFICATION_THRESHOLD = Decimal(
    os.environ.get('FUNDRAISE_BASIC_VERIFICATION_THRESHOLD', '50000')
)
# Свыше этой суммы — полная верификация с проверенным документом
FUNDRAISE_FULL_VERIFICATION_THRESHOLD = Decimal(
    os.environ.get('FUNDRAISE_FULL_VERIFICATION_THRESHOLD', '300000')
)
# Сумма, с которой заявка помечается для модератора как крупная
FUNDRAISE_LARGE_AMOUNT = Decimal(os.environ.get('FUNDRAISE_LARGE_AMOUNT', '500000'))

FUNDRAISE_MIN_DESCRIPTION_LENGTH = int(
    os.environ.get('FUNDRAISE_MIN_DESCRIPTION_LENGTH', '200')
)
# Сколько подтверждающих документов можно приложить к одному сбору
FUNDRAISE_MAX_DOCUMENTS = int(os.environ.get('FUNDRAISE_MAX_DOCUMENTS', '10'))

# ==================== ВНЕШНИЕ РЕСУРСЫ ====================
# Их нет и быть не должно.
#
# Шрифты и значки раздаются из main/static/vendor/. Раньше они грузились
# с fonts.googleapis.com и cdnjs.cloudflare.com, и на КАЖДОМ показе любой
# страницы — включая саму Политику конфиденциальности — IP-адрес и
# User-Agent посетителя уходили в США. Это трансграничная передача
# персональных данных (ст. 12 152-ФЗ) без уведомления РКН, а документы
# при этом утверждали обратное.
#
# Переключателя USE_EXTERNAL_CDN больше нет намеренно: настройка, которой
# можно снова включить передачу данных за рубеж, рано или поздно
# оказывается включённой. Обновить файлы шрифтов: manage.py vendor_static


# ==================== ANDROID-ПРИЛОЖЕНИЕ ====================
# Приложение — это тот же сайт, упакованный в APK (Trusted Web Activity):
# один код, одни правки, никакой второй реализации правил про деньги.

ANDROID_PACKAGE_NAME = os.environ.get('ANDROID_PACKAGE_NAME', 'ru.angelhelper.app')
ANDROID_APP_VERSION = os.environ.get('ANDROID_APP_VERSION', '1.0.0')

# Отпечаток SHA-256 ключа, которым подписана сборка. Берётся из вывода
# bubblewrap при сборке (или keytool -list -v -keystore ...).
# Несколько отпечатков перечисляются через запятую — например, ключ
# разработки и ключ выпуска.
#
# Пока пусто, /.well-known/assetlinks.json отдаёт 404: неверный отпечаток
# хуже отсутствующего — приложение молча покажет адресную строку, и
# причину будут искать неделю.
ANDROID_SIGNING_FINGERPRINTS = os.environ.get('ANDROID_SIGNING_FINGERPRINTS', '')

# Готовый APK для раздачи с сайта. Лежит вне статики: его меняют чаще,
# чем собирают статику, и скачивания видно в журнале веб-сервера.
ANDROID_APK_PATH = os.environ.get(
    'ANDROID_APK_PATH', str(BASE_DIR / 'app-release' / 'angelsheart.apk'),
)

# Внутренняя локация nginx, отдающая тот же файл (X-Accel-Redirect).
# Когда задана, питон файл не читает вовсе: он решает, отдавать ли, и
# сразу освобождает рабочий процесс. Без неё сборку отдаёт Django —
# годится для проверки, но десяток параллельных скачиваний с телефонов
# занимает все процессы, и сайт перестаёт отвечать.
#
#   location /internal-apk/ { internal; alias /srv/app-release/; }
#   ANDROID_APK_INTERNAL_LOCATION=/internal-apk/angelsheart.apk
ANDROID_APK_INTERNAL_LOCATION = os.environ.get('ANDROID_APK_INTERNAL_LOCATION', '')

# ==================== РЕКВИЗИТЫ ОПЕРАТОРА ====================
# Подставляются во все юридические документы из одного места.
# ч. 2 ст. 10 149-ФЗ обязывает раскрывать эти сведения на сайте,
# ч. 4 ст. 9 152-ФЗ — указывать их в согласии на обработку ПДн.
#
# ⚠️ ДО ПУБЛИКАЦИИ ЗАПОЛНИТЬ РЕАЛЬНЫМИ ДАННЫМИ.
# Документы с плейсхолдерами юридической силы не имеют.

OPERATOR = {
    'form': os.environ.get('OPERATOR_FORM', 'Индивидуальный предприниматель'),
    'name': os.environ.get('OPERATOR_NAME', '[ФАМИЛИЯ ИМЯ ОТЧЕСТВО]'),
    'short_name': os.environ.get('OPERATOR_SHORT_NAME', 'ИП [ФАМИЛИЯ И.О.]'),
    'ogrnip': os.environ.get('OPERATOR_OGRNIP', '[ОГРНИП]'),
    'inn': os.environ.get('OPERATOR_INN', '[ИНН]'),
    'address': os.environ.get('OPERATOR_ADDRESS', '[АДРЕС РЕГИСТРАЦИИ]'),
    'email': os.environ.get('OPERATOR_EMAIL', 'privacy@angel-helper.ru'),
    'support_email': os.environ.get('OPERATOR_SUPPORT_EMAIL', 'support@angel-helper.ru'),
    'phone': os.environ.get('OPERATOR_PHONE', '[ТЕЛЕФОН]'),
    'site': os.environ.get('SITE_URL', 'http://localhost:8000'),
    # Дата и номер уведомления Роскомнадзора об обработке ПДн (ст. 22 152-ФЗ)
    'rkn_notice': os.environ.get('OPERATOR_RKN_NOTICE', '[НЕ ПОДАНО]'),
    # Ответственный за организацию обработки ПДн (ч. 1 ст. 22.1 152-ФЗ).
    # На его адрес уходят оповещения о сроках по инцидентам.
    'dpo_name': os.environ.get('OPERATOR_DPO_NAME', ''),
    'dpo_email': os.environ.get('OPERATOR_DPO_EMAIL', ''),
}

# Версия юридических документов. При изменении текста версию надо поднять —
# согласия привязаны к версии, и пользователи должны принять новую редакцию.
# Редакция 1.1: раскрыты документы к сборам (в т. ч. сведения о здоровье),
# журнал доступа сотрудников к ПДн, порядок модерации сборов, порядок
# приостановления операций, подтверждение адреса почты и порядок погашения
# задолженности перед жертвователями. Номер не поднимался до 1.2, потому что
# редакция 1.1 ещё не вводилась в действие — она правится до публикации. Поднятие версии обязывает пользователей принять
# новую редакцию заново — в этом и смысл привязки согласий к версии.
LEGAL_DOCS_VERSION = os.environ.get('LEGAL_DOCS_VERSION', '1.1')
LEGAL_DOCS_UPDATED = os.environ.get('LEGAL_DOCS_UPDATED', '13 сентября 2026 г.')

# Сроки хранения персональных данных. Раньше сроков не было вовсе:
# данные хранились вечно, что нарушает п. 7 ч. 1 ст. 5 152-ФЗ
# («хранение не дольше, чем этого требуют цели обработки»).
DATA_RETENTION = {
    # 115-ФЗ, п. 4 ст. 7: документы по операциям — не менее 5 лет
    'financial_years': 5,
    # Журналы входов и событий безопасности
    'security_log_days': 365,
    # Сканы документов после завершения проверки
    'kyc_documents_days': 180,
    # Учётная запись после запроса на удаление
    'account_deletion_days': 30,
    # Журнал обращений сотрудников к ПДн. Дольше журнала входов: он нужен
    # для расследования инцидента, который может всплыть много позже.
    'pd_access_log_days': 1095,
    # Документы к сборам после завершения или отмены сбора. Срок короткий:
    # медицинская справка нужна только для проверки, а хранить её дальше
    # незачем — это специальная категория ПДн (ст. 10 152-ФЗ).
    'fundraise_documents_days': 30,
    # Документы к черновикам, которые автор так и не подал на проверку.
    # Без отдельного срока они не подпадали бы ни под одно правило и
    # хранились бы вечно.
    'abandoned_draft_days': 365,
}

# ==================== ШИФРОВАНИЕ ====================

from cryptography.fernet import Fernet


def _encryption_key():
    """
    Ключ Fernet для шифрования паспортных данных и платёжных реквизитов.

    В DEBUG выводится детерминированно из SECRET_KEY, чтобы данные,
    зашифрованные в прошлом запуске, оставались читаемыми.
    В проде требуется явный ключ: `python -c "from cryptography.fernet
    import Fernet; print(Fernet.generate_key().decode())"`.
    """
    raw = os.environ.get('ENCRYPTION_KEY')
    if raw:
        try:
            Fernet(raw.encode())
        except (ValueError, TypeError) as exc:
            raise ImproperlyConfigured(
                'ENCRYPTION_KEY не является корректным ключом Fernet '
                '(32 байта в urlsafe-base64).'
            ) from exc
        return raw
    if not DEBUG:
        raise ImproperlyConfigured('ENCRYPTION_KEY не задан при DEBUG=False.')
    import base64
    import hashlib
    digest = hashlib.sha256(SECRET_KEY.encode()).digest()
    return base64.urlsafe_b64encode(digest).decode()


ENCRYPTION_KEY = _encryption_key()

# ==================== INSTALLED APPS ====================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # DRF
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    # Без token_blacklist ROTATE_REFRESH_TOKENS/BLACKLIST_AFTER_ROTATION
    # ничего не делают, а разлогин не отзывает refresh-токен.
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'drf_yasg',
    
    # Наше приложение
    'main',
    # Сообщество: анкеты, поиск людей, чаты, группы
    'social',
]

# ==================== DRF ====================

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'main.api.pagination.CustomPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/day',
        'user': '1000/day',
        'donate': '50/hour',
        # Подбор пароля через API ограничивается отдельно от общего анонимного лимита
        'login': '10/hour',
        'register': '10/day',
        # Чаты, группы, поиск людей: открытый чат опрашивает сервер каждые
        # несколько секунд, общего лимита 1000 в сутки хватило бы на час
        'social': '2000/hour',
    },
}

# ==================== ЗАЩИТА ОТ ПЕРЕБОРА ПАРОЛЯ ====================

# Веб-форма входа не покрывается throttling'ом DRF, поэтому лимит свой.
LOGIN_MAX_ATTEMPTS = int(os.environ.get('LOGIN_MAX_ATTEMPTS', '10'))
LOGIN_ATTEMPT_WINDOW = int(os.environ.get('LOGIN_ATTEMPT_WINDOW', str(15 * 60)))
LOGIN_LOCKOUT_SECONDS = int(os.environ.get('LOGIN_LOCKOUT_SECONDS', str(15 * 60)))

# ==================== JWT ====================

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# ==================== SWAGGER ====================

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

# ==================== MIDDLEWARE ====================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # После AuthenticationMiddleware и MessageMiddleware: нужен request.user
    # и возможность объяснить пользователю, почему его перенаправили.
    'main.middleware.AccountBlockMiddleware',
]

# Раздача статики самим приложением — только в проде. Whitenoise стоит
# сразу за SecurityMiddleware, как требует его документация.
#
# В DEBUG его нет намеренно: статику там раздаёт сам Django, whitenoise
# ничего не добавляет, а числится он в requirements.txt в разделе «Прод».
# Пока он стоял здесь безусловно, машина разработчика без этого пакета
# просто не запускалась — ModuleNotFoundError вместо сервера.
if not DEBUG:
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')


# ==================== URLS ====================

ROOT_URLCONF = 'angelsheart.urls'

# ==================== TEMPLATES ====================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'main.context_processors.cookie_consent',
                'main.context_processors.legal',
            ],
        },
    },
]

# ==================== WSGI ====================

WSGI_APPLICATION = 'angelsheart.wsgi.application'

# ==================== DATABASE ====================

# ВАЖНО: на SQLite select_for_update() не создаёт построчных блокировок, поэтому
# вся защита финансовых операций от гонок работает только на PostgreSQL.
# SQLite допустим исключительно для локальной разработки.
if os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': int(os.environ.get('POSTGRES_CONN_MAX_AGE', '60')),
        }
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    raise ImproperlyConfigured(
        'При DEBUG=False нужна PostgreSQL: задайте POSTGRES_DB и остальные '
        'переменные подключения. SQLite не обеспечивает блокировку строк, '
        'на которой держится корректность денежных операций.'
    )

# ==================== AUTH ====================

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 10},
    },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ==================== INTERNATIONALIZATION ====================

LANGUAGE_CODE = 'ru-ru'
TIME_ZONE = 'Europe/Moscow'
USE_I18N = True
USE_TZ = True

# ==================== STATIC & MEDIA ====================

STATIC_URL = '/static/'
# main — приложение, и его static/ Django находит сам. Второе указание
# того же каталога в STATICFILES_DIRS приводило к дублям при collectstatic.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Раздача статики самим приложением. Без этого при DEBUG=False страницы
# остаются без стилей, шрифтов и значков до тех пор, пока кто-нибудь
# не настроит nginx, — а настроить его забывают.
if not DEBUG:
    STORAGES = {
        'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Сканы документов (KYC) не отдаются веб-сервером напрямую: они лежат вне
# MEDIA_ROOT и выдаются только вью с проверкой прав (main:kyc_document).
# На проде каталог не должен быть доступен через nginx.
PRIVATE_MEDIA_ROOT = Path(os.environ.get('PRIVATE_MEDIA_ROOT', BASE_DIR / 'private-media'))

# ==================== LOGIN/LOGOUT ====================

LOGIN_URL = 'main:login'
LOGIN_REDIRECT_URL = 'main:dashboard'
LOGOUT_REDIRECT_URL = 'main:login'

# ==================== SESSIONS ====================

SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 недели
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_REMEMBER_ME_AGE = 30 * 24 * 60 * 60  # 30 дней

# ==================== ПЛАТЕЖНЫЕ СИСТЕМЫ ====================

# ЮKassa
YOOKASSA_SHOP_ID = os.environ.get('YOOKASSA_SHOP_ID', '')
YOOKASSA_SECRET_KEY = os.environ.get('YOOKASSA_SECRET_KEY', '')

# Режим: 'test' или 'live'
PAYMENT_MODE = os.environ.get('PAYMENT_MODE', 'test')
USE_REAL_PAYMENTS = os.environ.get('USE_REAL_PAYMENTS', 'False') == 'True'

# Симуляция пополнения баланса без обращения к платёжной системе.
# Разрешена только в DEBUG: в проде это была бы неограниченная эмиссия денег.
ALLOW_SIMULATED_TOPUP = DEBUG and not USE_REAL_PAYMENTS
# Потолок суммарного «нарисованного» баланса на пользователя в режиме симуляции
SIMULATED_TOPUP_TOTAL_LIMIT = Decimal(os.environ.get('SIMULATED_TOPUP_TOTAL_LIMIT', '100000'))

# URL для возврата после оплаты
PAYMENT_SUCCESS_URL = os.environ.get('PAYMENT_SUCCESS_URL', 'http://localhost:8000/payment/success/')
PAYMENT_CANCEL_URL = os.environ.get('PAYMENT_CANCEL_URL', 'http://localhost:8000/payment/cancel/')

# Диапазоны, с которых ЮKassa шлёт уведомления. Подписи у неё нет, поэтому
# проверка источника строится на IP + повторном запросе платежа через API.
# Актуальный список: https://yookassa.ru/developers/using-api/webhooks
YOOKASSA_WEBHOOK_IPS = [
    ip.strip()
    for ip in os.environ.get(
        'YOOKASSA_WEBHOOK_IPS',
        '185.71.76.0/27,185.71.77.0/27,77.75.153.0/25,77.75.156.11,'
        '77.75.156.35,77.75.154.128/25,2a02:5180::/32',
    ).split(',')
    if ip.strip()
]

SITE_URL = os.environ.get('SITE_URL', 'http://localhost:8000')

# ==================== ЛИМИТЫ ВЕРИФИКАЦИИ ====================
# Единственное место, где эти цифры заданы. main/payments/verification.py и
# main/payments/withdrawals.py читают их отсюда — раньше значения были
# продублированы в трёх файлах.

UNVERIFIED_LIMITS = {
    'daily_withdrawal': Decimal('1000'),
    'monthly_withdrawal': Decimal('5000'),
    'single_withdrawal': Decimal('500'),
    'daily_payment': Decimal('10000'),
}

BASIC_VERIFIED_LIMITS = {
    'daily_withdrawal': Decimal('10000'),
    'monthly_withdrawal': Decimal('50000'),
    'single_withdrawal': Decimal('5000'),
    'daily_payment': Decimal('50000'),
}

FULL_VERIFIED_LIMITS = {
    'daily_withdrawal': Decimal('100000'),
    'monthly_withdrawal': None,
    'single_withdrawal': Decimal('50000'),
    'daily_payment': Decimal('500000'),
}

VERIFICATION_LIMITS = {
    'unverified': UNVERIFIED_LIMITS,
    'basic': BASIC_VERIFIED_LIMITS,
    'full': FULL_VERIFIED_LIMITS,
}

# ==================== EMAIL ====================

EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Консольный бэкенд в проде опаснее отсутствия почты: send_mail «успешно»
# пишет письмо в stdout, сервис считает пользователя уведомлённым и
# закрывает срок по п. 9.2 оферты, а человек не получает ничего.
if not DEBUG and EMAIL_BACKEND.endswith('console.EmailBackend'):
    raise ImproperlyConfigured(
        'EMAIL_BACKEND=console при DEBUG=False: письма о блокировках, выплатах '
        'и восстановлении пароля никуда не уйдут. Задайте SMTP-бэкенд.'
    )
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@angel-helper.ru')

# Как часто можно просить письмо с подтверждением адреса. Без ограничения
# форма повторной отправки годится для рассылки по чужим адресам.
# Дополнительные домены одноразовой почты, через запятую. Встроенный
# список в main/utils/email_domains.py заведомо неполон.
DISPOSABLE_EMAIL_DOMAINS = os.environ.get('DISPOSABLE_EMAIL_DOMAINS', '')

EMAIL_CONFIRMATION_RESEND_SECONDS = int(
    os.environ.get('EMAIL_CONFIRMATION_RESEND_SECONDS', '300')
)

# ==================== CACHE ====================

# Счётчики попыток входа живут в кеше. LocMemCache не разделяется между
# воркерами и обнуляется при перезапуске, поэтому в проде нужен Redis —
# иначе защита от перебора обходится попаданием в соседний процесс.
if os.environ.get('REDIS_URL'):
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': os.environ['REDIS_URL'],
        }
    }
else:
    if not DEBUG:
        raise ImproperlyConfigured(
            'При DEBUG=False задайте REDIS_URL: локальный кеш процесса не годится '
            'для счётчиков попыток входа и антифрода.'
        )
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'angelsheart-dev',
        }
    }

# ==================== LOGGING ====================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {'format': '{levelname} {asctime} {module} {message}', 'style': '{'},
        'simple': {'format': '{levelname} {message}', 'style': '{'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'simple'},
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'security.log'),
            'formatter': 'verbose',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
        },
        'withdrawal_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'withdrawals.log'),
            'formatter': 'verbose',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOG_DIR / 'errors.log'),
            'formatter': 'verbose',
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
        },
    },
    'loggers': {
        'security': {'handlers': ['console', 'file'], 'level': 'INFO', 'propagate': True},
        'withdrawals': {'handlers': ['console', 'withdrawal_file'], 'level': 'INFO', 'propagate': True},
        'django': {'handlers': ['console', 'error_file'], 'level': 'INFO', 'propagate': True},
        'django.request': {'handlers': ['error_file'], 'level': 'ERROR', 'propagate': False},
    },
}

# ==================== DEFAULT ====================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'