# Generated by Django 5.2.18 on 2026-10-07 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_seed_interests'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_hidden',
            field=models.BooleanField(default=False, verbose_name='Скрыто'),
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Спам или реклама'), ('abuse', 'Оскорбления или травля'), ('fraud', 'Мошенничество'), ('illegal', 'Запрещённый контент'), ('other', 'Другое')], max_length=10, verbose_name='Причина')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Комментарий')),
                ('message_text', models.TextField(verbose_name='Текст сообщения на момент жалобы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Принята — сообщение скрыто'), ('rejected', 'Отклонена')], db_index=True, default='new', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='social.chatmessage')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения')),
            ],
            options={
                'verbose_name': 'Жалоба на сообщение',
                'verbose_name_plural': 'Жалобы на сообщения',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('message', 'reporter'), name='unique_message_report')],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Блокировка',
                'verbose_name_plural': 'Чёрный список',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('blocker', 'blocked'), name='unique_user_block')],
            },
        ),
    ]
