# Generated by Django 5.2.18 on 2026-10-07 10:09

import main.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_blocks_and_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, storage=main.storage.PrivateMediaStorage(), upload_to='chat/%Y/%m/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='socialprofile',
            name='avatar',
            field=models.ImageField(blank=True, storage=main.storage.PrivateMediaStorage(), upload_to='avatars/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
