# Generated by Django 5.2.18 on 2026-10-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
